/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.evaluator;

import java.awt.CardLayout;

/**
 *
 * @author Admin
 */
public class ComparisonTable extends javax.swing.JFrame {
    IOFile file = new IOFile();
    public String urlFile1 = "C:/Users/Admin/Documents/NetBeansProjects/snake/src/com/evaluator/data1.txt";
    public String urlFile2 = "C:/Users/Admin/Documents/NetBeansProjects/snake/src/com/evaluator/data2.txt";
    public String urlFile3 = "C:/Users/Admin/Documents/NetBeansProjects/snake/src/com/evaluator/data3.txt";
    public String urlFile4 = "C:/Users/Admin/Documents/NetBeansProjects/snake/src/com/evaluator/data4.txt";
    /**
     * Creates new form ComparisonTable
     */
    public ComparisonTable() {
        initComponents();
        setTitle("ComparisonTable");
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"BFS Proposal", file.ReadNumOR(urlFile1), file.ReadScore(urlFile1), file.ReadTime(urlFile1), file.ReadStep(urlFile1)},
                {"Greedy base on BFS", file.ReadNumOR(urlFile2), file.ReadScore(urlFile2), file.ReadTime(urlFile2), file.ReadStep(urlFile2)},
                {"A star Proposal", file.ReadNumOR(urlFile3), file.ReadScore(urlFile3), file.ReadTime(urlFile3), file.ReadStep(urlFile3)},
                {"Greedy base on A star", file.ReadNumOR(urlFile4), file.ReadScore(urlFile4), file.ReadTime(urlFile4), file.ReadStep(urlFile4)}
            },
            new String [] {
                "Algorithm", "Numbers of run", "Score", "Times", "Steps"
            }
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable1.setMaximumSize(new java.awt.Dimension(500, 500));
        jTable1.setRowHeight(40);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComparisonTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComparisonTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComparisonTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComparisonTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComparisonTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
